V2
1156UnderControl/scouting-24 pull request #3
Opened 2024-01-28 23:43 UTC by ljb6

2024-01-29 13:46 UTC, rlawisch requested changes
This time I made a proper code review, so that you can also gain experience with it. Those are not top-down decisions: all coments I put can be discussed in their own thread, or accepted and addressed through new commits and a new request for review in the same PR.

2024-01-29 13:46 UTC, rlawisch commented on src/lib/components/MatchSelection.svelte
> -		<RadioItem bind:group={tournamentLevel} name="justify" value={'Qualification'}>Quali</RadioItem>
This should keep as Quali with an I, to follow english rules (Qualy with an Y only exists in Brazil, as a margarine brand)

2024-01-29 13:46 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
> +	import { Step } from '@skeletonlabs/skeleton';
Keep a blank line between imports from external libraries and imports from our code

2024-01-29 13:46 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
>  		if (!attemptedClimbing) {
We should handle the newly added radio group value here, to not let bad data interfere with our statistics: set to blank string if `!attemptedClimbing`, else set to a default value (I would put the center, as it is the easier to climb).

2024-01-29 13:46 UTC, rlawisch commented on src/lib/components/RadioGroup.svelte
>  	<p>{legend}</p>
this should be indented further to be viewed as "inside the if block"

2024-01-29 13:46 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
> +		{value: "Midright", label: "MR"},
I would stick with `Center-left`, `Center` and `Center-right`, with a `-` to separate and because `Mid` is not as usual in English as it is in Portuguese

2024-01-29 13:46 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
> +
This blank line shouldn't exist

2024-01-29 13:46 UTC, rlawisch commented on src/lib/steps/ExtraInformationStep.svelte
> +	<section class="justify-items-left grid gap-3">
Great work with the alignment!

2024-01-29 16:10 UTC, ljb6 commented on src/lib/steps/EndgameStep.svelte
>  		if (!attemptedClimbing) {
I resolved the other problems, I'm just unsure if this is right.

2024-01-29 16:12 UTC, ljb6 commented on src/lib/steps/EndgameStep.svelte
>  		if (!attemptedClimbing) {
```
export let userSelectedClimbStage = "Center";

function handleAttemptedClimbingChange() {
		if (!attemptedClimbing) {
			failedClimbing = false;
			userSelectedClimbStage = "";
		} 
	}
```

2024-01-29 17:36 UTC, rlawisch requested changes
Much better! Thanks for the ongoing effort

2024-01-29 17:36 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
> +	export let userSelectedClimbStage = "Center";
This should be moved up with the rest of the props (marked by `export let`), so that we can know what props this component exports without needing to read the code further

2024-01-29 17:36 UTC, rlawisch commented on src/lib/steps/EndgameStep.svelte
>  		if (!attemptedClimbing) {
This! And an `else` block to set a default value for the `userSelectedClimbStage`, so that it never gets in an inconsistent state in which the user could send the answers with this variable empty.

2024-01-29 23:07 UTC, ljb6 commented
All problems are resolved, reviewwwww

2024-01-30 01:54 UTC, rlawisch approved these changes

2024-01-30 01:55 UTC, merged